// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI_60y539anckQmQollUjkKkm5nAuTxek',
    appId: '1:167400318057:android:a39014900e31b9fc35aef8',
    messagingSenderId: '167400318057',
    projectId: 'kaps-ai-gnnovation',
    storageBucket: 'kaps-ai-gnnovation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRGhSeAZpFscebJBO85MYYfWUSL_C8NQ',
    appId: '1:167400318057:ios:d0eb4a1c660a371f35aef8',
    messagingSenderId: '167400318057',
    projectId: 'kaps-ai-gnnovation',
    storageBucket: 'kaps-ai-gnnovation.appspot.com',
    androidClientId: '167400318057-mq99fm9tm5kp0o8qg3oila98u0v9mpgp.apps.googleusercontent.com',
    iosClientId: '167400318057-ekk91us2nvmngjcgsm5lu44bu3h7uv8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

}